version: '3.7'

services:
  postgres:
    image: postgres:14
    container_name: postgres_app
    ports:
      - "5432:5432"
    volumes:
      - .data/:/tmp
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: app_password
      PGDATA: /tmp

  app:
    restart: always
    build: .
    env_file:
      - .env
    volumes:
      - .:/backend
    command: >
      sh -c " python manage.py migrate && python manage.py runserver 0.0.0.0:8000 "
    ports:
      - "8000:8000"
    depends_on:
      - postgres
